# .readthedocs.yml

version: 2

sphinx:
  configuration: docs/conf.py  # Path to your conf.py file

python:
  version: "3.9"
  install:
    - requirements: docs/requirements.txt  # Path to your requirements.txt file

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

formats:
  - pdf
  - epub

# Command to install Asciidoctor, adjust if needed for your project
# Read the Docs does not support installing Ruby gems directly, so you must
# use a custom build process or Docker image if you need Asciidoctor gems.
commands:
  - apt-get update && apt-get install -y asciidoctor